import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-basic-text',
  templateUrl: './basic-text.component.html',
  styleUrls: ['./basic-text.component.css']
})
export class BasicTextComponent implements OnInit {

  constructor() { }

  textData: { heading: string, content: string }[] = [];

  ngOnInit() {
    this.textData.push({heading: "Capricorn", content: "Capricorn (♑) is the tenth astrological sign in the zodiac, originating from the constellation of Capricornus, the horned goat. It spans the 270–300th degree of the zodiac, corresponding to celestial longitude. Under the tropical zodiac, the sun transits this area from about December 21 to January 21 the following year,[2] and under the sidereal zodiac, the sun transits the constellation of Capricorn from approximately January 16 to February 16. In astrology, Capricorn is considered an earth sign, negative sign,[3][4] and one of the four cardinal signs. Capricorn is said to be ruled by the planet Saturn. In Vedic Astrology Capricorn was associated with the Crocodile but modern astrologers consider Capricorn as Sea goat. Its symbol is based on the Sumerians' primordial god of wisdom and waters, Enki,[5] with the head and upper body of a goat and the lower body and tail of a fish."});
    this.textData.push({heading: "Aquarius", content: "Aquarius (♒) is the eleventh astrological sign in the Zodiac, originating from the constellation Aquarius. Under the tropical zodiac, the sun is in Aquarius between about January 21 and about February 20,[2][3] while under the sidereal Zodiac, the sun is in Aquarius from approximately February 15 to March 14, depending on the leap year."});
    this.textData.push({heading: "Pisces", content: "Pisces (♓️) (/ˈpaɪsiːz/;[2][3] Ancient Greek: Ἰχθύες Ikhthyes) is the twelfth astrological sign in the Zodiac. It spans 330° to 360° of celestial longitude. Under the tropical zodiac the sun transits this area between February 19 and March 20. [a] In Sidereal astrology, the Sun currently transits the constellation of Pisces from approximately March 12 to April 18.[4][5] In classical interpretations, the symbol of the fish is derived from the ichthyocentaurs, who aided Aphrodite when she was born from the sea.According to some tropical astrologers, the current astrological age is the Age of Pisces,[7] while others maintain that it is the Age of Aquarius."});
    this.textData.push({heading: "Aries", content: "Aries (♈) /ˈɛəriːz/ (meaning ram) is the first astrological sign in the zodiac, spanning the first 30 degrees of celestial longitude (0°≤ λ <30°). Under the tropical zodiac, the Sun transits this sign from approximately March 20 to April 21 each year.[2] This time duration is exactly the first month of the Solar Hijri calendar (Hamal/Farvardin/Wray). The symbol of the ram is based on the Chrysomallus, the flying ram that provided the Golden Fleece."});
    this.textData.push({heading: "Taurus", content: "Taurus (Greek for Ταύρος (Tavros) (Latin for The Bull) is the second astrological sign in the present zodiac. It spans from 30° to 60° of the zodiac. This sign belongs to the Earth element or triplicity, and therefore has a feminine or negative polarity. It has a Fixed modality, quality or quadruplicity. It is a Venus-ruled sign just like Libra. It is the sign where the Moon has its exaltation at exactly 3°. The Sun transits in the sign of Taurus from approximately April 21 until May 21 in western astrology. People born between these dates, depending on which system of astrology they subscribe to, may be called Taureans."});
    this.textData.push({heading: "Gemini", content: "Gemini (pronunciation: /ˈdʒɛmɪnaɪ/ JEM-in-eye (♊)[2] is the third astrological sign in the zodiac, originating from the constellation of Gemini. Under the tropical zodiac, the sun transits this sign between about May 21 and June 21. Gemini is represented by the twins Castor and Pollux,[3] known as the Dioscuri, who were granted shared half-immortality after the death of the mortal brother, Castor."});
    this.textData.push({heading: "Cancer", content: "Cancer (♋️) is the fourth astrological sign in the Zodiac, originating from the constellation of Cancer. It spans from 90° to 120° celestial longitude. Under the tropical zodiac, the Sun transits this area between approximately June 21 and July 23,[2] and under the sidereal zodiac, the Sun transits this area between approximately July 21 and August 9."});
    this.textData.push({heading: "Leo", content: "Leo (♌) (Greek: Λέων, Leōn), is the fifth astrological sign of the zodiac, originating from the constellation of Leo. It comes after Cancer and before Virgo. The traditional Western zodiac associates Leo with the period between July 23 and August 22,[2] and the sign spans the 120th to 150th degree of celestial longitude"});
    this.textData.push({heading: "Virgo", content: "Virgo (♍) (Greek: Παρθένος, Parthenos), is the sixth astrological sign in the Zodiac. It spans the 150-180th degree of the zodiac. Under the tropical zodiac, the Sun transits this area on average between August 23 and September 22,[2] and the Sun transits the constellation of Virgo from approximately September 16 to October 30.[3] Individuals born during these dates, depending on which system of astrology they subscribe to, may be called Virgos[4] or Virgoans.[5] The symbol of the maiden is based on Astraea."});
    this.textData.push({heading: "Libra", content: "Libra (♎) is the seventh astrological sign in the Zodiac. It spans 180°–210° celestial longitude. Under the tropical zodiac, the Sun transits this area on average between (northern autumnal equinox) September 23 and October 23,[2][3] and under the sidereal zodiac, the sun currently transits the constellation of Libra from approximately October 31 to November 22."});
    this.textData.push({heading: "Scorpio", content: "Scorpio is the eighth astrological sign in the Zodiac, originating from the constellation of Scorpius. It spans 210°–240° ecliptic longitude. Under the tropical zodiac (most commonly used in Western astrology), the Sun transits this area on average from October 23 to November 22.[2] Under the sidereal zodiac (most commonly used in Hindu astrology), the Sun is in Scorpio from approximately November 16 to December 15."});
    this.textData.push({heading: "Sagittarius", content: "Sagittarius (♐) (Greek: Τοξότης Toxotes, Latin: Sagittarius) is the ninth astrological sign, which is associated with the constellation Sagittarius and spans 240–270th degrees of the zodiac. Under the tropical zodiac, the sun transits this sign between approximately November 23 and December 21. Greek mythology associates Sagittarius with the centaur Chiron, who mentored Achilles, a Greek hero of the Trojan War, in archery."});
  }

}
